# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'annuaire.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Annuaire(object):
    """
        Class View :
        Visuelle de l'annuaire. Deux fenêtres : celle principale & la boite de dialogue 
        afin de créer un nouveau contact. 
    """

    def setupUi(self, Annuaire):

        Annuaire.setObjectName("Annuaire")
        Annuaire.setWindowModality(QtCore.Qt.NonModal)
        Annuaire.setEnabled(True)
        Annuaire.resize(675, 634)
        Annuaire.setMinimumSize(QtCore.QSize(0, 0))
        Annuaire.setMaximumSize(QtCore.QSize(675, 4910))
        Annuaire.setStyleSheet("")

        self.centralwidget = QtWidgets.QWidget(Annuaire)
        self.centralwidget.setObjectName("centralwidget")
        self.centralwidget.setStyleSheet("background-color: rgb(255, 245, 223);")

        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")

        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")

        self.searchBar = QtWidgets.QTextEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("PilGi")
        font.setPointSize(36)

        self.searchBar.setFont(font)
        self.searchBar.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.searchBar.setMouseTracking(False)
        self.searchBar.setOverwriteMode(True)
        self.searchBar.setTabStopWidth(81)
        self.searchBar.setTextInteractionFlags(QtCore.Qt.TextEditorInteraction)
        self.searchBar.setObjectName("searchBar")

        self.horizontalLayout_3.addWidget(self.searchBar)

        self.searchButton = QtWidgets.QPushButton(self.centralwidget)
        self.searchButton.setEnabled(True)

        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 254, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 254, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)

        self.searchButton.setPalette(palette)
        self.searchButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.searchButton.setFocusPolicy(QtCore.Qt.TabFocus)
        self.searchButton.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.searchButton.setWhatsThis("")
        self.searchButton.setAutoFillBackground(False)
        self.searchButton.setStyleSheet("border: none")
        self.searchButton.setInputMethodHints(QtCore.Qt.ImhNone)
        self.searchButton.setText("")

        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("loupeContact2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)

        self.searchButton.setIcon(icon)
        self.searchButton.setIconSize(QtCore.QSize(70, 70))
        self.searchButton.setCheckable(False)
        self.searchButton.setObjectName("searchButton")

        self.horizontalLayout_3.addWidget(self.searchButton)

        spacerItem = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)

        self.horizontalLayout_3.addItem(spacerItem)

        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout.setObjectName("verticalLayout")

        self.greenBar = QtWidgets.QLabel(self.centralwidget)
        self.greenBar.setMinimumSize(QtCore.QSize(0, 10))
        self.greenBar.setStyleSheet("background-color: #4EBD6B")
        self.greenBar.setText("")
        self.greenBar.setObjectName("greenBar")
        self.verticalLayout.addWidget(self.greenBar)

        self.verticalLayout_4.addLayout(self.verticalLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, -1, -1, 5)
        self.horizontalLayout.setObjectName("horizontalLayout")

        self.listLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("PilGi")
        font.setPointSize(17)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)

        self.listLabel.setFont(font)
        self.listLabel.setStyleSheet("font: 17pt \"PilGi\";\n""")
        self.listLabel.setObjectName("listLabel")

        self.horizontalLayout.addWidget(self.listLabel, 0, QtCore.Qt.AlignHCenter)

        self.detailLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("PilGi")
        font.setPointSize(17)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)

        self.detailLabel.setFont(font)
        self.detailLabel.setStyleSheet("font: 17pt \"PilGi\";")
        self.detailLabel.setObjectName("detailLabel")

        self.horizontalLayout.addWidget(self.detailLabel, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")

        self.listContact = QtWidgets.QListWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listContact.sizePolicy().hasHeightForWidth())
        self.listContact.setSizePolicy(sizePolicy)
        self.listContact.setObjectName("listContact")
        self.listContact.setStyleSheet("selection-background-color: #4EBD6B;")
        self.horizontalLayout_2.addWidget(self.listContact)
        spacerItem2 = QtWidgets.QSpacerItem(20, 600, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setContentsMargins(-1, -1, 20, -1)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")

        self.labelNom = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("PilGi")
        font.setPointSize(18)
        self.labelNom.setFont(font)
        self.labelNom.setObjectName("labelNom")
        self.horizontalLayout_5.addWidget(self.labelNom)
        spacerItem3 = QtWidgets.QSpacerItem(49, 25, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)

        self.editName = QtWidgets.QLineEdit(self.centralwidget)
        self.editName.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(15)
        self.editName.setFont(font)
        self.editName.setStyleSheet("border : none; background : transparent")
        self.editName.setText("")
        self.editName.setObjectName("editName")
        self.horizontalLayout_5.addWidget(self.editName)
        self.verticalLayout_9.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")

        self.labelPrenom = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("PilGi")
        font.setPointSize(18)
        self.labelPrenom.setFont(font)
        self.labelPrenom.setObjectName("labelPrenom")
        self.horizontalLayout_8.addWidget(self.labelPrenom)
        spacerItem4 = QtWidgets.QSpacerItem(28, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem4)

        self.editFirstname = QtWidgets.QLineEdit(self.centralwidget)
        self.editFirstname.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(15)

        self.editFirstname.setFont(font)
        self.editFirstname.setStyleSheet("border : none;\n"
"background:transparent")
        self.editFirstname.setObjectName("editFirstname")
        self.horizontalLayout_8.addWidget(self.editFirstname)
        self.verticalLayout_9.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.labelTel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("PilGi")
        font.setPointSize(18)

        self.labelTel.setFont(font)
        self.labelTel.setObjectName("labelTel")
        self.horizontalLayout_9.addWidget(self.labelTel)
        spacerItem5 = QtWidgets.QSpacerItem(7, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem5)

        self.editPhone = QtWidgets.QLineEdit(self.centralwidget)
        self.editPhone.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(15)
        self.editPhone.setFont(font)
        self.editPhone.setStyleSheet("border : none; background:transparent")
        self.editPhone.setObjectName("editPhone")
        self.horizontalLayout_9.addWidget(self.editPhone)
        self.verticalLayout_9.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")

        self.labelMail = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("PilGi")
        font.setPointSize(18)
        self.labelMail.setFont(font)
        self.labelMail.setObjectName("labelMail")
        self.horizontalLayout_10.addWidget(self.labelMail)
        spacerItem6 = QtWidgets.QSpacerItem(35, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem6)

        self.editMail = QtWidgets.QLineEdit(self.centralwidget)
        self.editMail.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(15)
        self.editMail.setFont(font)
        self.editMail.setStyleSheet("border : none;background:transparent")
        self.editMail.setObjectName("editMail")
        self.horizontalLayout_10.addWidget(self.editMail)
        self.verticalLayout_9.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")

        self.labelNaissance = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("PilGi")
        font.setPointSize(18)
        font.setKerning(True)

        self.labelNaissance.setFont(font)
        self.labelNaissance.setObjectName("labelNaissance")
        self.horizontalLayout_6.addWidget(self.labelNaissance)

        self.editBirthday = QtWidgets.QDateEdit(self.centralwidget)
        self.editBirthday.setVisible(False)
        self.editBirthday.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(15)
        self.editBirthday.setFont(font)
        self.editBirthday.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.editBirthday.setStyleSheet("border : none;background:transparent")
        self.editBirthday.setObjectName("editBirthday")
        self.horizontalLayout_6.addWidget(self.editBirthday)
        spacerItem10 = QtWidgets.QSpacerItem(156, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem10)

        self.verticalLayout_9.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setContentsMargins(-1, -1, 20, -1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")

        self.labelAdresse = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("PilGi")
        font.setPointSize(18)
        self.labelAdresse.setFont(font)
        self.labelAdresse.setObjectName("labelAdresse")
        self.verticalLayout_5.addWidget(self.labelAdresse)
        spacerItem8 = QtWidgets.QSpacerItem(20, 150, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem8)
        self.horizontalLayout_4.addLayout(self.verticalLayout_5)
        spacerItem9 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem9)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")

        self.editAddress = QtWidgets.QTextEdit(self.centralwidget)
        self.editAddress.setEnabled(False)
        self.editAddress.setStyleSheet("border : none;background:transparent")
        self.editAddress.setObjectName("editAddress")
        self.verticalLayout_3.addWidget(self.editAddress)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout_9.addLayout(self.horizontalLayout_4)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")

        self.tickButton = QtWidgets.QPushButton(self.centralwidget)
        self.tickButton.setVisible(False)
        self.tickButton.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.tickButton.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.tickButton.setAccessibleDescription("")
        self.tickButton.setStyleSheet("background-color:transparent; border:none")
        self.tickButton.setInputMethodHints(QtCore.Qt.ImhNone)
        self.tickButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("tick.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tickButton.setIcon(icon1)
        self.tickButton.setIconSize(QtCore.QSize(30, 30))
        self.tickButton.setCheckable(False)
        self.tickButton.setAutoDefault(False)
        self.tickButton.setDefault(False)
        self.tickButton.setFlat(False)
        self.tickButton.setObjectName("tickButton")
        self.verticalLayout_2.addWidget(self.tickButton)
        self.verticalLayout_9.addLayout(self.verticalLayout_2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_9)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)

        Annuaire.setCentralWidget(self.centralwidget)

        self.menubar = QtWidgets.QMenuBar(Annuaire)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 675, 22))
        self.menubar.setObjectName("menubar")

        self.fileMenu = QtWidgets.QMenu(self.menubar)
        self.fileMenu.setObjectName("fileMenu")

        self.helpMenu = QtWidgets.QMenu(self.menubar)
        self.helpMenu.setObjectName("helpMenu")
        Annuaire.setMenuBar(self.menubar)

        self.statusbar = QtWidgets.QStatusBar(Annuaire)
        self.statusbar.setObjectName("statusbar")
        Annuaire.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(Annuaire)

        self.toolBar.setObjectName("toolBar")
        Annuaire.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)

        self.newContact = QtWidgets.QAction(Annuaire)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.newContact.setIcon(icon2)
        font = QtGui.QFont()
        font.setFamily("PilGi")
        font.setPointSize(18)
        self.newContact.setFont(font)
        self.newContact.setObjectName("newContact")

        self.modifyContact = QtWidgets.QAction(Annuaire)
        self.modifyContact.setCheckable(True)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("modifyContact.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.modifyContact.setIcon(icon3)
        font = QtGui.QFont()
        font.setFamily("PilGi")
        font.setPointSize(18)
        self.modifyContact.setFont(font)
        self.modifyContact.setObjectName("modifyContact")

        self.deleteContact = QtWidgets.QAction(Annuaire)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.deleteContact.setIcon(icon4)
        font = QtGui.QFont()
        font.setFamily("PilGi")
        font.setPointSize(18)
        self.deleteContact.setFont(font)
        self.deleteContact.setObjectName("deleteContact")

        self.exportList = QtWidgets.QAction(Annuaire)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("export-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exportList.setIcon(icon6)
        font = QtGui.QFont()
        font.setFamily("PilGi")
        font.setPointSize(18)
        self.exportList.setFont(font)
        self.exportList.setObjectName("exportList")

        self.importList = QtWidgets.QAction(Annuaire)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("import-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.importList.setIcon(icon7)
        font = QtGui.QFont()
        font.setFamily("PilGi")
        font.setPointSize(18)
        self.importList.setFont(font)
        self.importList.setObjectName("importList")


        self.utilisation = QtWidgets.QAction(Annuaire)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("pointInterrogation.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.utilisation.setIcon(icon5)
        font = QtGui.QFont()
        font.setFamily("PilGi")
        font.setPointSize(18)
        self.utilisation.setFont(font)
        self.utilisation.setObjectName("utilisation")
        self.fileMenu.addAction(self.newContact)
        self.fileMenu.addAction(self.modifyContact)
        self.fileMenu.addAction(self.deleteContact)
        self.fileMenu.addAction(self.exportList)
        self.fileMenu.addAction(self.importList)
        self.helpMenu.addAction(self.utilisation)
        self.menubar.addAction(self.fileMenu.menuAction())
        self.menubar.addAction(self.helpMenu.menuAction())
        self.toolBar.addAction(self.newContact)
        self.toolBar.addAction(self.modifyContact)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.deleteContact)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.exportList)
        self.toolBar.addAction(self.importList)

        self.retranslateUi(Annuaire)
        QtCore.QMetaObject.connectSlotsByName(Annuaire)
        

        self.DialogCreateContact = QtWidgets.QDialog()
        self.DialogCreateContact.setObjectName("DialogCreateContact")
        self.DialogCreateContact.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(self.DialogCreateContact)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lName = QtWidgets.QLabel(self.DialogCreateContact)
        font = QtGui.QFont()
        font.setFamily("PilGi")
        font.setPointSize(18)
        self.lName.setFont(font)
        self.lName.setObjectName("lName")
        self.horizontalLayout_6.addWidget(self.lName)
        spacerItem = QtWidgets.QSpacerItem(34, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.eName = QtWidgets.QLineEdit(self.DialogCreateContact)
        self.eName.setStyleSheet("border : none ")
        self.eName.setObjectName("eName")
        self.horizontalLayout_6.addWidget(self.eName)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lFirstname = QtWidgets.QLabel(self.DialogCreateContact)
        font = QtGui.QFont()
        font.setFamily("PilGi")
        font.setPointSize(18)
        self.lFirstname.setFont(font)
        self.lFirstname.setObjectName("lFirstname")
        self.horizontalLayout_5.addWidget(self.lFirstname)
        spacerItem1 = QtWidgets.QSpacerItem(12, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.eFirstname = QtWidgets.QLineEdit(self.DialogCreateContact)
        self.eFirstname.setStyleSheet("border : none ")
        self.eFirstname.setObjectName("eFirstname")
        self.horizontalLayout_5.addWidget(self.eFirstname)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lTel = QtWidgets.QLabel(self.DialogCreateContact)
        font = QtGui.QFont()
        font.setFamily("PilGi")
        font.setPointSize(18)
        self.lTel.setFont(font)
        self.lTel.setObjectName("lTel")
        self.horizontalLayout_4.addWidget(self.lTel)
        spacerItem2 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.eTel = QtWidgets.QLineEdit(self.DialogCreateContact)
        self.eTel.setStyleSheet("border : none ")
        self.eTel.setObjectName("eTel")
        self.horizontalLayout_4.addWidget(self.eTel)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lMail = QtWidgets.QLabel(self.DialogCreateContact)
        font = QtGui.QFont()
        font.setFamily("PilGi")
        font.setPointSize(18)
        self.lMail.setFont(font)
        self.lMail.setObjectName("lMail")
        self.horizontalLayout_3.addWidget(self.lMail)
        spacerItem3 = QtWidgets.QSpacerItem(28, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.eMail = QtWidgets.QLineEdit(self.DialogCreateContact)
        self.eMail.setStyleSheet("border : none ")
        self.eMail.setObjectName("eMail")
        self.horizontalLayout_3.addWidget(self.eMail)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lBirthday = QtWidgets.QLabel(self.DialogCreateContact)
        font = QtGui.QFont()
        font.setFamily("PilGi")
        font.setPointSize(18)
        self.lBirthday.setFont(font)
        self.lBirthday.setObjectName("lBirthday")
        self.horizontalLayout_2.addWidget(self.lBirthday)
        spacerItem4 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)

        self.eBirthday = QtWidgets.QDateEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(15)
        self.eBirthday.setFont(font)
        self.eBirthday.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.eBirthday.setStyleSheet("border : none;background:transparent")
        self.eBirthday.setObjectName("eBirthday")
        spacerItem10 = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)

        self.horizontalLayout_2.addWidget(self.eBirthday)
        self.horizontalLayout_2.addItem(spacerItem10)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lAddress = QtWidgets.QLabel(self.DialogCreateContact)
        font = QtGui.QFont()
        font.setFamily("PilGi")
        font.setPointSize(18)
        self.lAddress.setFont(font)
        self.lAddress.setObjectName("lAddress")
        self.verticalLayout_4.addWidget(self.lAddress)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem5)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        spacerItem6 = QtWidgets.QSpacerItem(14, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.eAddress = QtWidgets.QTextEdit(self.DialogCreateContact)
        self.eAddress.setStyleSheet("border : none ")
        self.eAddress.setObjectName("eAddress")
        self.horizontalLayout.addWidget(self.eAddress)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.DialogCreateContact)
        self.buttonBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateDialogUi(self.DialogCreateContact)


    def retranslateUi(self, Annuaire):

        _translate = QtCore.QCoreApplication.translate
        Annuaire.setWindowTitle(_translate("Annuaire", "Annuaire"))
        self.searchBar.setHtml(_translate("Annuaire", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'PilGi\'; font-size:36pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-style:italic; color:#a4a4a4;\">Rechercher ...</span></p></body></html>"))
        self.searchButton.setToolTip(_translate("Annuaire", "Valider votre recherche"))
        self.listLabel.setText(_translate("Annuaire", "Liste des contacts (A-Z)"))
        self.detailLabel.setText(_translate("Annuaire", "Détail d\'une fiche contact"))
        self.labelNom.setText(_translate("Annuaire", "Nom:"))
        self.labelPrenom.setText(_translate("Annuaire", "Prénom:"))
        self.labelTel.setText(_translate("Annuaire", "Téléphone:"))
        self.labelMail.setText(_translate("Annuaire", "E-mail:"))
        self.labelNaissance.setText(_translate("Annuaire", "Naissance:"))
        self.labelAdresse.setText(_translate("Annuaire", "Adresse:"))
        self.fileMenu.setTitle(_translate("Annuaire", "Fichier"))
        self.helpMenu.setTitle(_translate("Annuaire", "Aide"))
        self.toolBar.setWindowTitle(_translate("Annuaire", "toolBar"))
        self.newContact.setText(_translate("Annuaire", "Nouvelle Fiche"))
        self.modifyContact.setText(_translate("Annuaire", "Modifier une fiche"))
        self.deleteContact.setText(_translate("Annuaire", "Supprimer une fiche"))
        self.exportList.setText(_translate("Annuaire", "Exporter annuaire"))
        self.importList.setText(_translate("Annuaire", "Importer annuaire"))
        self.utilisation.setText(_translate("Annuaire", "Utilisation"))

    def retranslateDialogUi(self, DialogCreateContact):
        _translate = QtCore.QCoreApplication.translate
        self.DialogCreateContact.setWindowTitle(_translate("self.DialogCreateContact", "Nouveau contact"))
        self.lName.setText(_translate("self.DialogCreateContact", "Nom*"))
        self.lFirstname.setText(_translate("self.DialogCreateContact", "Prénom*"))
        self.lTel.setText(_translate("self.DialogCreateContact", "Téléphone"))
        self.lMail.setText(_translate("self.DialogCreateContact", "E-mail"))
        self.lBirthday.setText(_translate("self.DialogCreateContact", "Naissance"))
        self.lAddress.setText(_translate("self.DialogCreateContact", "Adresse"))

